spring:
  east-china:
    kafka:
      enable: true
      bootstrap-servers: 192.168.56.15:9092,192.168.56.16:9092,192.168.56.17:9092 # kafka集群信息，多个用逗号间隔
      jaas:
        options:
          username: admin
          password: admin123
      ssl:
        trust-store-location: D:/kafka_2.12-2.3.0/certs/kafka.client.truststore.jks
        trust-store-password: 123456
        keystore.key:
            password: 123456
            alias: localhost
            location: D:/kafka_2.12-2.3.0/certs/kafka.client.keystore.jks
      properties:
        sasl:
          mechanism: PLAIN
        security:
          protocol: SASL_PLAINTEXT
        ssl:
          endpoint-identification-algorithm: ""
      # 消费者
      consumer:
        group-id: TestGroup
        enable-auto-commit: true
        auto-offset-reset: earliest
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        type: batch
        concurrency: 3
      producer:
        batch-size: 16
        buffer-memory: 1024
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        retries: 0
